In [1]:
from pyoculus.problems import AnalyticCylindricalBfield
from pyoculus.solvers import PoincarePlot, FixedPoint, Manifold
import matplotlib.pyplot as plt
import numpy as np
import pickle

In [5]:
separatrix = {"type": "circular-current-loop", "amplitude": -10, "R": 6, "Z": -5.5}
maxwellboltzmann = {"m": 18, "n": -3, "d": np.sqrt(2), "type": "maxwell-boltzmann", "amplitude": 1e-6}

# Creating the pyoculus problem object, adding the perturbation here use the R, Z provided as center point
pyoproblem = AnalyticCylindricalBfield.without_axis(
    6,
    0,
    0.91,
    0.6,
    perturbations_args=[separatrix],
    Rbegin=1,
    Rend=8,
    niter=800,
    guess=[6.41, -0.7],
    tol=1e-9,
)

# # Adding perturbation after the object is created uses the found axis as center point
pyoproblem.add_perturbation(maxwellboltzmann)

### Finding the X-point
print("\nFinding the X-point\n")

# set up the integrator for the FixedPoint
iparams = dict()
iparams["rtol"] = 1e-13

pparams = dict()
pparams["nrestart"] = 0
pparams["niter"] = 300

# set up the FixedPoint object
fixedpoint = FixedPoint(pyoproblem, pparams, integrator_params=iparams)

# find the X-point
guess = [6.21560891, -4.46981856]
print(f"Initial guess: {guess}")

fixedpoint.compute(guess=guess, pp=0, qq=1, sbegin=4, send=9, tol=1e-10)

if fixedpoint.successful:
    results = [list(p) for p in zip(fixedpoint.x, fixedpoint.y, fixedpoint.z)]
else:
    raise ValueError("X-point not found")

# Set up the manifold
iparams = dict()
iparams["rtol"] = 1e-13
manifold = Manifold(fixedpoint, pyoproblem, integrator_params=iparams)

# Choose the tangles to work with
manifold.choose(0, 0)

0 - dr : 0.010422282084043258
1 - RZ : [ 6.41409394 -0.69368043]
1 - dr : 6.293042617255254e-06
2 - RZ : [ 6.41409781 -0.69367863]
2 - dr : 9.776471937205409e-12
0 - dr : 9.776471937205409e-12

Finding the X-point

Initial guess: [6.21560891, -4.46981856]
0 - [DeltaR, DeltaZ] : [0.3681251  0.29366272] - dtheta : 0.10118852399832656
0 - [StepR, StepZ]: [-0.0236111  -0.02026724]
1 - RZ : [ 6.19199781 -4.4900858 ] - rhotheta : [ 3.80289834 -1.6292324 ]
1 - [DeltaR, DeltaZ] : [-0.16107199 -0.17325409] - dtheta : 0.03779092276387552
1 - [StepR, StepZ]: [0.00559025 0.00256556]
2 - RZ : [ 6.19758806 -4.48752024] - rhotheta : [ 3.80001455 -1.62780323]
2 - [DeltaR, DeltaZ] : [-0.01704153 -0.02901229] - dtheta : 0.004010692864668375
2 - [StepR, StepZ]: [ 0.00597728 -0.00824633]
3 - RZ : [ 6.20356534 -4.49576657] - rhotheta : [ 3.80791237 -1.62611269]
3 - [DeltaR, DeltaZ] : [0.00039688 0.00018237] - dtheta : 0.0001014219681712003
3 - [StepR, StepZ]: [ 5.74398406e-05 -1.32091755e-04]
4 - RZ : [ 6.

In [ ]:
fig = pickle.load(open("manifold_05070828.pkl", "rb"))
ax = fig.gca()

In [ ]:
np.exp(np.log([2.8417682373597518e-06, 2.662504808775117e-08]))

In [6]:
manifold.find_clinics(n_points = 6, n_s = 8, n_u = 4)

2024-05-13 09:47:26 [info     ] Search for minimum of the linear error succeeded, epsilon = 2.05960e-07
2024-05-13 09:47:26 [info     ] Search for minimum of the linear error succeeded, epsilon = 7.38313e-08
2024-05-13 09:47:26 [debug    ] Guess - 2.8417685686942265e-06, 1.0187051441516095e-06
2024-05-13 09:47:26 [debug    ] Bounds - ((2.0595969838636592e-07, 5.889496835774819e-06), (7.38313201069366e-08, 2.1112416084101558e-06))
2024-05-13 09:47:26 [debug    ] n_s, n_u - 8, 4
2024-05-13 09:47:26 [debug    ] Inside : (2.841768568694225e-06, 1.0187051441516093e-06)
2024-05-13 09:47:31 [debug    ] Returns - (array([ 7.67878879, -3.2224385 ]), array([ 6.58295684, -4.17777162]), array([1.09583195, 0.95533313]))
2024-05-13 09:47:31 [debug    ] Inside : (1.6515886549188005e-06, 0.0003896725876360781)
2024-05-13 09:47:33 [debug    ] Returns - (array([ 8.03376901, -2.80810259]), array([8.16117219, 1.26265593]), array([-0.12740318, -4.07075852]))
2024-05-13 09:47:33 [debug    ] Inside : (7.3985

In [7]:
manifold.clinics

[(2.9910377953910173e-06,
  9.026868390339808e-06,
  2.9910377953910173e-06,
  array([ 7.0072546 , -3.83723985]),
  array([ 7.00725468, -3.83724002])),
 (5.2309346160738794e-06,
  0.0001475819905612363,
  5.23093461581068e-06,
  array([ 6.28864648, -4.42060306]),
  array([ 6.28864585, -4.42060243])),
 (9.147547558405266e-06,
  8.439701573574154e-05,
  9.147547558473835e-06,
  array([ 6.34605779, -4.37151072]),
  array([ 6.34605821, -4.37151111])),
 (1.5998048101693762e-05,
  4.825863919665952e-05,
  1.5998048102173278e-05,
  array([ 6.43638123, -4.29634477]),
  array([ 6.43638093, -4.29634452])),
 (2.633031871268059e-05,
  2.932161187195347e-05,
  2.633031871272753e-05,
  array([ 6.55409355, -4.20090117]),
  array([ 6.55409355, -4.20090117])),
 (4.891515942545299e-05,
  1.5783386912953914e-05,
  4.891515942555779e-05,
  array([ 6.76007712, -4.03666906]),
  array([ 6.76007701, -4.03666887]))]

In [ ]:
# fig = pickle.load(open("manifold_05070825.pkl", "rb"))
fig = pickle.load(open("manifold_05070828.pkl", "rb"))
ax = fig.gca()

In [ ]:
marker = ["+", "o", "s", "p", "P", "*", "X", "D", "d", "^", "v", "<", ">"]
for i, clinic in enumerate(manifold.clinics):
    eps_s_i, eps_u_i = clinic[1:3]

    n_s, n_u = 8, 8
    
    hs_i = manifold.integrate(manifold.rfp_s + eps_s_i * manifold.vector_s, n_s, -1)
    hu_i = manifold.integrate(manifold.rfp_u + eps_u_i * manifold.vector_u, n_u, 1)
    ax.scatter(hs_i[0,:], hs_i[1,:], marker=marker[i], color="purple", zorder=10)
    ax.scatter(hu_i[0,:], hu_i[1,:], marker=marker[i], color="blue", zorder=10)

In [ ]:
# ax.set_xlim(6, 8)
# ax.set_ylim(-5, -3.5)
# ax.set_xlim(6, 9)
# ax.set_ylim(-5, -1)
fig

In [8]:
manifold.resonance_area()

2024-05-13 09:53:21 [info     ] Forward integration goes beyond stable saddle point.
2024-05-13 09:53:21 [debug    ] rfp_s: [ 6.20362279 -4.49589868], rze_end: [ 6.20361752 -4.49590344], rze_forward: [ 6.20362245 -4.49589857]
2024-05-13 09:53:21 [info     ] Backward integration goes beyond unstable saddle point.
2024-05-13 09:53:21 [debug    ] rfp_u: [ 6.20362279 -4.49589868], rze_end: [ 6.20362303 -4.49589908], rze_backward: [ 6.20362288 -4.49589862]
2024-05-13 09:53:21 [info     ] Potential integration completed for homo/hetero-clinic point of order : 2.991e-06
2024-05-13 09:53:22 [info     ] Forward integration goes beyond stable saddle point.
2024-05-13 09:53:22 [debug    ] rfp_s: [ 6.20362279 -4.49589868], rze_end: [ 6.20368574 -4.49584154], rze_forward: [ 6.20362491 -4.49589652]
2024-05-13 09:53:22 [info     ] Backward integration goes beyond unstable saddle point.
2024-05-13 09:53:22 [debug    ] rfp_u: [ 6.20362279 -4.49589868], rze_end: [ 6.20362217 -4.49589759], rze_backward: 

(array([ 9.50002676e-05,  3.53513886e-05,  5.70839095e-05, -1.89833434e-05,
        -7.10809697e-06,  6.62329182e-07]),
 [[array([-21.31606083,  -8.86284547,  -1.99538197,  -9.82411158,
          -12.25100652,   9.2401393 ,  12.30031195,  12.42167336,
           12.42594362]),
   array([  9.85399899, -10.7320259 , -12.36379613, -12.42390934,
          -12.42601578])],
  [array([-16.01153411, -13.94235857, -14.14022508,   2.35888721,
          -14.56161493,  -7.91950973,  10.5077536 ,  12.35402563,
           12.4235624 ,  12.42592759]),
   array([ -9.56990023, -12.31729854, -12.42227511, -12.42595831,
          -12.42608641])],
  [array([-21.72457054,  -7.00301802, -17.94266925,   4.62686077,
          -17.69069367,  -3.36797987,  11.2945058 ,  12.3848339 ,
           12.42464658,  12.42603327]),
   array([ -7.72085141, -12.23630848, -12.41941794, -12.42585836,
          -12.42608279])],
  [array([-26.05805518,  -3.01568538, -17.70153617,   4.09529875,
          -18.88830215,   0.90973

In [9]:
areas = manifold.areas
areas

array([ 9.50002676e-05,  3.53513886e-05,  5.70839095e-05, -1.89833434e-05,
       -7.10809697e-06,  6.62329182e-07])

In [10]:
areas[areas > 0].sum()

0.0001880978948136658

In [11]:
areas[areas < 0].sum()

-2.6091440339826022e-05

In [12]:
areas.sum()

0.00016200645447383977